name: Email workflow                         

on:
  schedule:
    - cron: "*/5 * * * *"  # Every 5 minutes

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.7"

      - name: Run the Python script 
        env:
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: |
          python "email_script.py"
