name: Selenium Script Manual Run

on:
  workflow_dispatch:
    
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checking out repo
      uses: actions/checkout@v3
      
    - name: Setting up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11.7"
        
    - name: Removing previous Chrome
      run: sudo apt purge google-chrome-stable  
  
    - name: Installing packages
      run: pip install chromedriver-autoinstaller selenium beautifulsoup4 pyvirtualdisplay
      
    - name: Installing xvfb
      run: sudo apt-get install xvfb

    - name: Running Python script
      env:  
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}  
      run: python "CTC Banners - Test.py"
      
