name: Python Script Schedule Run                          

on:
  schedule:
    - cron: "0 19 * * *"                                                                    

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11.7"                                                           

    - name: Install dependencies                         
      run: pip install yfinance pandas duckdb google-auth-httplib2 google-auth-oauthlib google-api-python-client pretty-html-table

    - name: Run the Python script 
      env:
          READ_WRITE_TO_GSHEET_APIS_JSON: ${{ secrets.READ_WRITE_TO_GSHEET_APIS_JSON }}    
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}                                            
      run: python "Furniture - Daily Stocks.py"                                              

